version: '3.8'
services:
  # MongoDB database service
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  # Backend service (Node.js/Express)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mern_db
    depends_on:
      - mongo
    networks:
      - mern-network

  # Frontend service (React)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      # --- IMPORTANT CHANGE: Pass REACT_APP_API_URL as a build argument ---
      args:
        REACT_APP_API_URL: http://10.255.114.96:5000 # This value will be available during the build
    container_name: frontend_container
    ports:
      - "3000:80"
    # --- Remove 'environment' for REACT_APP_API_URL here, as it's for runtime, not buildtime ---
    # environment:
    #   REACT_APP_API_URL: http://localhost:5000 # This line is no longer needed here for buildtime variables
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
